name:                tac-interpreter
version:             0.1.0.0
github:              "LDiazN/tac-interpreter"
license:             BSD3
author:              
  - "Luis Diaz"
  - "Jesús Wahrman"
  - "Neil Villamizar"
maintainer:          "ldiazn98@gmail.com"
copyright:           "2021 Luis Diaz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/LDiazN/tac-interpreter#readme>

dependencies:
- base >= 4.7 && < 5
- array
- directory
- hspec
- extra
- containers >= 0.6.1
- mtl
- text
- ansi-terminal

library:
  source-dirs: src

executables:
  taci:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall


    dependencies:
    - tac-interpreter

tests:
  tac-interpreter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tac-interpreter
